dist: focal
language: node_js
node_js:
    - lts/*
    - node
sudo: false
install:
    - npm config set prefer-offline false
    - npm install
script:
    - echo -e "\x1b\x5b35;1m*** Linting...\x1b\x5b0m"
    - npm run lint -- --report-unused-disable-directives --max-warnings 0
    - echo -e "\x1b\x5b35;1m*** Linting complete\x1b\x5b0m"
