language: node_js
node_js:
    - 10
sudo: false
cache:
  directories:
    - $(npm config get cache)
install:
    - npm config set prefer-offline true
    - npm install
script:
    - echo -e "\x1b\x5b35;1m*** Linting...\x1b\x5b0m"
    - npm run lint -- --max-warnings 0
    - echo -e "\x1b\x5b35;1m*** Linting complete\x1b\x5b0m"
